### ISSUE TITLE
Error running from source

### ISSUE THREAD

**Issue by patriciorivera** [RickMcConney/PenPlotter#1]
Hi. Great Job!! Im getting this error running v0.5 from source processing 2.2.1. on mac OS. Thanks!

<img width="892" alt="captura de pantalla 2015-08-28 a las 21 39 08" src="https://cloud.githubusercontent.com/assets/5302658/9561316/652f1ffe-4e40-11e5-9861-fd0a72f26e8c.png">

**Comment by RickMcConney** [comment]
You may be running against a different version of the controlP5 library. I have uploaded the version of the library I am using to the V05 release, Try downloading the libraries.zip file and unzipping it in the processing/libraries directory.

**Comment by RickMcConney** [comment]
Leave open until fix confirmed

**Comment by patriciorivera** [comment]
I confirm that work fine only with controlP5 version 2.2.5. By the way, I have tested versions 0.5.4, 1.5.2 and 2.0.4, failing in all cases.
