### ISSUE TITLE
Cannot find a class or type named "Handle 

### ISSUE THREAD

**Issue by 3dcasemonster** [RickMcConney/PenPlotter#10]
In processing 2 error occurs on compilation , **"Cannot find a class or type named 'Handle'.**

**Comment by RickMcConney** [comment]
You may be missing a compile dependency please see the compiling section for a list of dependencies and how to install them. I just downloaded and recompiled with the latest version of processing and had no errors. I also packaged the dependencies in a library.zip file that can be downloaded from the releases tab  incase any of the dependencies get an incompatible update.

**Comment by 3dcasemonster** [comment]
Im up and running. Thanks, for the fast response
