### ISSUE TITLE
Hardware Setup?

### ISSUE THREAD

**Issue by krummrey** [RickMcConney/PenPlotter#3]
Hi I was wondering if you have a brief description of your hardware setup? 
The board and motors are like the Polargraph? 
How are the motors connected to the Ramps?
A brief description would help. Thanks.

**Comment by RickMcConney** [comment]
Yes there is no change in the hardware to use the original firmware and my ramps version. The left motor is connected to E1 and the right motor to Y not sure why this was originally chosen but I modified the pins.h file to make it compatible with the original setup.
