### ISSUE TITLE
G1 doesnt work for Z and E

### ISSUE THREAD

**Issue by patriciorivera** [RickMcConney/PenPlotter#9]
Hi Rick, i realized that G1 commands only work for X and Y, but not for Z and E. 

if i uncomment line 461 on commands.cpp: 
if(Printer::setDestinationStepsFromGCode(com)) // For X Y Z E F 

they work but i lost polar conversion.

Its ok if I use G0 but the idea is to use G1 commands to get coordinated movements.
 
Any suggestion to get  synchronized movement including Z and E value?

Thanks a lot.
Patricio

**Comment by RickMcConney** [comment]
Sorry, the Z and E are not supported with the polar conversion. You would need to look for the POLAR defines as areas where I changed the code to support polar and see if there is a way to add what you need.
